<template>
  <div>
    <svg width="10" height="15" xmlns="http://www.w3.org/2000/svg">
      <g>
        <rect
          fill="#fff"
          id="canvas_background"
          height="17"
          width="12"
          y="-1"
          x="-1"
        />
        <g
          display="none"
          overflow="visible"
          y="0"
          x="0"
          height="100%"
          width="100%"
          id="canvasGrid"
        >
          <rect
            fill="url(#gridpattern)"
            stroke-width="0"
            y="0"
            x="0"
            height="100%"
            width="100%"
          />
        </g>
      </g>
      <g>
        <ellipse
          stroke="#0093d2"
          ry="2.625"
          rx="2.625"
          id="svg_2"
          cy="3.625"
          cx="5.125"
          stroke-width="1.5"
          fill="#0093d2"
        />
        <line
          stroke="#0093d2"
          stroke-linecap="undefined"
          stroke-linejoin="undefined"
          id="svg_5"
          y2="17.30125"
          x2="5.25"
          y1="4.5"
          x1="5.25"
          stroke-width="1.5"
          fill="none"
        />
      </g>
    </svg>
  </div>
</template>
